### ISSUE TITLE
`GET` request sent with action configured with `method: POST JSON`

### ISSUE THREAD

**Issue by wuservices** [managed-components/http-request#7]
This is a followup to a [#zaraz Discord post](https://discord.com/channels/595317990191398933/917505178016579605/1178903028649168927). @bjesus asked me to file an issue and report here.

**Problem**
`GET` request is sent for an action when `POST JSON` method is selected. This is isolated to 1 of 5 similar actions within the same HTTP Request Tool.
![image](https://github.com/managed-components/http-request/assets/190434/3ce29332-618c-42aa-b77c-cebdd33b4530)

**Observation**
This was first observed due to seeing `GET` requests with 404 responses (our endpoint only accepts `POST`), and very large query strings with all the data.

However, we have 5 similar actions configured with the same HTTP Request tool, and the other 4 are sending `POST` as expected.

**Background**
`HTTP Request` tool is set up with 5 actions to the same endpoint, all set to `method: POST JSON`, but for just 1 of the actions, Zaraz is sending a `GET` with query string params.

Here's a comparison of a working action (left) and the failing action that's sending a `GET` instead of a `POST` (right). I reordered the keys from the exported JSON for consistency, otherwise this is unmodified.
<img width="960" alt="image" src="https://github.com/managed-components/http-request/assets/190434/8b265dbd-9999-496a-831e-f552fc3edd21">

**Troubleshooting steps attempted**
Based on the code that chooses the method, it seems impossible for this behavior to be inconsistent given our config.
https://github.com/managed-components/http-request/blob/ef2767450fe61ca2995e91906f78526f0d950aca/src/index.ts#L6

I was thinking that some deployment or infrastructure could be in a weird state, so I hoped that changing some stuff would force a better state, but _none of these were unsuccessful_.

1. Change `tikTokEvent` custom param to ensure the log events are correlated with the action in the UI and that the deployments are changing something
2. Add another action with a similar config (thinking the original one could be "stuck" in a weird state)
3. Delete the bad actions, deploy, recreate with a new name, deploy

**Comment by wuservices** [comment]
@bjesus I should have realized earlier that the event failing has `method` defined in its payload. This MC is probably seeing that value, then sending `GET` because it does not start with `post`. Then it also deletes that from the request body, along with anything named `endpoint` or `ecommerce`.

Is there a way for the MC to differentiate between the options set for the MC in the UI like the `method` vs the payload?

If not, could these be namespaced with something like `__zarazHttpMethod` to ensure that payloads don't clash with the settings?

For context, I'm passing `method`, because it's one of the [GA4 recommended params](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtm#sign_up) for sign ups, but I imagine this is a common enough name in a lot of data.

**Comment by Refaerds** [comment]
Hi @wuservices, from now on you get use `__setting_method` or `__setting_endpoint` fields to define http request method and endpoint. In this case, `method` and `endpoint` fields can be used for other values and will remain in the request payload. The release with this change is ongoing and should be available to all users within a few hours.

**Comment by wuservices** [comment]
Thanks for the fix @Refaerds and @jonnyparris. Does this change the setting keys set by the UI at all, or just allow you to manually set additional keys?

I've tried the latter and that has fixed my specific issue (making it impossible to force `post_json`), however I don't see a way to avoid setting the original keys in the UI (`method` and `endpoint`). If my assumption is right, does the manifest force you to set the old keys, which would overwrite anything in the user-supplied payload?

Here's an example, where you can't avoid setting `method` and `endpoint`:

<img width="894" alt="image" src="https://github.com/managed-components/http-request/assets/190434/468e9069-bdf0-461a-9884-c88992aa1752">

**Comment by Refaerds** [comment]
hello @wuservices , sorry for the delayed response. Indeed, we're yet to take additional steps (including changes in the UI) in order to switch to __setting_ prefixed fields completely. But this will take some time. Meanwhile, if you want to override the `method` value, you can do this manually:
1. export your config (on Zaraz > Settings > Advanced page)
2. modify the value
3. save your config directly through a http request (https://developers.cloudflare.com/api/operations/put-zones-zone_identifier-zaraz-config)

**Comment by wuservices** [comment]
@Refaerds thanks for clarifying. Good to know, and I can confirm that manual update process has been working for us.

I had expected those to be in the manifest, but maybe it's a separate Cloudflare internal config for the official integrations?
